# Generated by Django 4.2.3 on 2023-10-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_remove_newprofile_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalQAFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('law', models.CharField(blank=True, max_length=200, null=True)),
                ('prec', models.CharField(blank=True, max_length=200, null=True)),
                ('embedding', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
